# Generated by Django 3.2.9 on 2021-11-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
