# Generated by Django 3.2.9 on 2021-11-20 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='watched_at',
            field=models.DateField(default=datetime.date(2021, 11, 20)),
        ),
    ]
