# Generated by Django 3.2.9 on 2021-11-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_review_watched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
