# Generated by Django 3.2.9 on 2021-11-24 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_review_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='watched_at',
            field=models.DateField(default=datetime.date(2021, 11, 24)),
        ),
    ]
